branches:
  only:
    - /^dockerize.*$/
matrix:
  include:
  - os: linux
    env: 
      - REDHAT_BUILD: true
      - RUN_OPTS: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    services:
      - docker
  - os: linux
    env:
      - REDHAT_BUILD: false
      - OSX_BUILD: false
    services:
      - mongod
  - os: osx
    osx_image: xcode7.1
    env:
      - REDHAT_BUILD: false
      - OSX_BUILD: true
before_install: ./travis/script.sh
script: rspec
after_failure: "cat /Users/travis/build/NREL/OpenStudio-server/spec/files/logs/mongod.log"
