branches:
  only:
    - /^dockerize.*$/
matrix:
  include:
  - os: linux
    env: REDHAT_BUILD=true
  - os: linux
    env:
      - REDHAT_BUILD=false
      - OSX_BUILD=false
  - os: osx
    osx_image: xcode7.1
    env:
      - REDHAT_BUILD=false
      - OSX_BUILD=true
services:
  - docker
  - mongod
before_install: ./travis/script.sh
script: rspec
