matrix:
  include:
  - os: linux
    env: REDHAT_BUILD=true
  - os: osx
    osx_image: xcode7.1
    env: REDHAT_BUILD=false
  - os: osx
    osx_image: xcode8
    env: REDHAT_BUILD=false
services:
  - docker
  - mongod
before_install:
  script:
    travis/script.sh
