version: 1.0.{build}-{branch}

environment:
  USE_TESTING_TIMEOUTS: "true"
  matrix:
    - RUBY_VERSION: "224-x64"

clone_folder: C:\projects\openstudio-server

install:
  - C:\projects\openstudio-server\ci\appveyor\setup.cmd

build: off

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - mongod.exe --version

test_script:
  - ps: C:\projects\openstudio-server\ci\appveyor\test.ps1

on_failure:
  - C:\projects\openstudio-server\ci\appveyor\print_logs.cmd

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
