# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '2'
services:
  web:
    build:
      args:
        rails_env: docker-test
        bundle_args: ''
    environment:
     - CI
     - COVERALLS_REPO_TOKEN
     - CIRCLECI
    volumes:
      - ./reports:/opt/openstudio/reports
      - osdata:/mnt/openstudio
    command: /usr/local/bin/run-server-tests
  rserve:
    volumes:
      - osdata:/mnt/openstudio
volumes:
  osdata:
    external: true

