# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '2'
services:
  db:
    image: mongo:latest
  web:
    build:
      context: .
      args:
        rails_env: docker-test
        bundle_args: ''
    image: nrel/openstudio-server:latest
    environment:
      - CI
      - COVERALLS_REPO_TOKEN
      - CIRCLECI
    links:
      - db
      - rserve
    ports:
      - "8080:80"
    volumes:
      - ./reports:/opt/openstudio/reports
      - osdata:/mnt/openstudio
    command: /usr/local/bin/run-server-tests
  rserve:
    build: ./docker/R
    image: nrel/openstudio-rserve:latest
    volumes:
      - osdata:/mnt/openstudio
volumes:
  osdata:
    external: true
