# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '3.4'
services:
  db:
    image: mongo:3.4.10
  queue:
    image: redis:4.0.6
  web:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker-test
        bundle_args: ''
    environment:
      - CI
      - COVERALLS_REPO_TOKEN
      - TRAVIS=true
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - TRAVIS_PULL_REQUEST
    links:
      - db
      - queue
      - rserve
    ports:
      - "8080:80"
    volumes:
      - ./reports:/opt/openstudio/reports
      - osdata:/mnt/openstudio
    command: /usr/local/bin/run-server-tests
  web-background:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker-test
        bundle_args: ''
    environment:
      - CI
      - COVERALLS_REPO_TOKEN
      - TRAVIS=true
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - TRAVIS_PULL_REQUEST
    links:
      - db
      - web
      - queue
    volumes:
      - osdata:/mnt/openstudio
    command: /usr/local/bin/start-web-background
  worker:
    image: nrel/openstudio-server:latest
    environment:
      - QUEUES=simulations
      - COUNT=1
    volumes:
      - /mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - queue
      - rserve
    command: /usr/local/bin/start-workers  
  rserve:
    image: nrel/openstudio-rserve:latest
    build: ./docker/R
    volumes:
      - osdata:/mnt/openstudio
volumes:
  osdata:
    external: true
