defaults: &defaults
  sim_root_path: /mnt/openstudio

development:
  <<: *defaults
  ruby_bin_dir: /Users/nlong/.rbenv/shims
  sim_root_path: ':rails_root/../worker-nodes'

docker:
  <<: *defaults
  ruby_bin_dir: /usr/local/ruby

test:
  <<: *defaults

production:
  <<: *defaults