defaults: &defaults
  sim_root_path: /mnt/openstudio
  ruby_bin_dir: ':ruby_bin_dir'
  os_server_host_url: <%= ENV['OS_SERVER_HOST_URL'] %>
  rails_log_path: ':rails_root/log'

development:
  <<: *defaults
  ruby_bin_dir: ':ruby_bin_dir'
  sim_root_path: ':rails_root/../worker-nodes'
  os_server_host_url: 'http://localhost:3000'

docker:
  <<: *defaults
  ruby_bin_dir: /usr/local/ruby

test:
  <<: *defaults
  os_server_host_url: 'http://localhost:3000'
  sim_root_path: ':rails_root/../worker-nodes'

production:
  <<: *defaults

local:
  <<: *defaults
  sim_root_path: ':rails_root/../worker-nodes'
  rails_log_path: <%= ENV['OS_SERVER_LOG_PATH'] %>
