defaults: &defaults
  sim_root_path: /mnt/openstudio
  ruby_bin_dir: ':ruby_bin_dir'

development:
  <<: *defaults
  ruby_bin_dir: ':ruby_bin_dir'
  sim_root_path: ':rails_root/../worker-nodes'

docker:
  <<: *defaults
  ruby_bin_dir: /usr/local/ruby

test:
  <<: *defaults

production:
  <<: *defaults