development:
  sessions:
    default:
      database: os_dev
      hosts:
        - localhost:27017
      options:
  options:
    allow_dynamic_fields: true
    raise_not_found_error: false
docker:
  sessions:
    default:
      database: os_docker
      hosts:
        - db:27017
      options:
  options:
    allow_dynamic_fields: true
    raise_not_found_error: false
production:
  sessions:
    default:
      database: os_dev
      hosts:
        - localhost:27017
      options:
  options:
    allow_dynamic_fields: true
    raise_not_found_error: false
test:
  sessions:
    default:
      database: os_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
local:
    sessions:
      default:
        database: <%= ENV['OS_SERVER_DATABASE_NAME'] %>
        hosts:
          - localhost:<%= ENV['OS_SERVER_MONGO_PORT'] %>
        options:
    options:
      allow_dynamic_fields: true
      raise_not_found_error: false
